version: "3.9"

services:
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - wordpress
    environment:
      - DOMAIN=wordpress
      - PORT=80
      - SUBDOMAIN=trustedlogin
      - DEBUG=true
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    restart: always
    depends_on:
      - wordpress

  wordpress:
    depends_on:
      wpdb:
        condition: service_healthy
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/trustedlogin-vendor
    ports:
      - "8200:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* WordPress logging- Not Shown, but logged. */
        define( 'WP_DEBUG_LOG', 'wp-content/plugins/trustedlogin-vendor/wpdebug.log' );
        define( 'WP_DEBUG_DISPLAY', true );
        /* ngrok wp urls overrides */
        define('WP_SITEURL', 'https://trustedlogin.ngrok.io/');
        define('WP_HOME', 'https://trustedlogin.ngrok.io/' );

  wpdb:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  wpcli:
    image: wordpress:cli
    depends_on:
      - wpdb
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/trustedlogin-vendor
      - ./db:/var/www/html/db
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      ABSPATH: /usr/src/wordpress/
    depends_on:
      wpdb:
        condition: service_healthy

  phpunit:
    command:
      - bash
    depends_on:
      - testwpdb
    environment:
      DATABASE_PASSWORD: examplepass
      DATABASE_HOST: testwpdb
    image: futureys/phpunit-wordpress-plugin
    stdin_open: true
    tty: true
    volumes:
      - ./:/plugin

  testwpdb:
      environment:
        MYSQL_ROOT_PASSWORD: examplepass
      image: mariadb:10.5.8

volumes:
  db_data: {}
  wordpress_data: {}
