version: "3.9"

services:

  # Tunnel


  # WordPress
  ## PHP + Core
  wordpress:
    image: wordpress:latest
    ## Wait to start until database server is started.
    depends_on:
      wpdb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      ## Map this directory into the plugin directory
      - ./:/var/www/html/wp-content/plugins/trustedlogin-vendor
    ports:
      - "8100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* WordPress logging- Not Shown, but logged. */
        define( 'WP_DEBUG_LOG', 'wp-content/plugins/trustedlogin-vendor/wpdebug.log' );
        define( 'WP_DEBUG_DISPLAY', true );
        //If true, TrustedLogin\Vendor\ErrorHandler will handle all errors
        define( 'TRUSTEDLOGIN_DEBUG', true );

  ## Database for WordPress site
  wpdb:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
  ## WPCli for WordPress site
  wpcli:
    image: wordpress:cli
    ## Wait to start until database server is started.
    depends_on:
      wpdb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      ## Map this directory into the plugin directory
      - ./:/var/www/html/wp-content/plugins/trustedlogin-vendor
      - ./db:/var/www/html/db
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      ABSPATH: /usr/src/wordpress/

  # Integration Testing - Tests that run in phpunit with WordPress + MySQL
  ## Runner for phpunit
  phpunit:
    command:
      - bash
    ## Wait to start until the database server for testing is ready.
    depends_on:
      - testwpdb
    environment:
      DATABASE_PASSWORD: examplepass
      DATABASE_HOST: testwpdb

    image: josh412/wp-phpunit:php-${PHP_IMAGE_TAG-7.4}-wp-${WORDPRESS_VERSION-latest}
    stdin_open: true
    tty: true
    volumes:
      ## Map this directory into the test plugin directory
      - ./:/plugin
  ## Database for testing
  testwpdb:
      environment:
        MYSQL_ROOT_PASSWORD: examplepass
      image: mariadb:10.5.8

volumes:
  db_data: {}
  wordpress_data: {}
