name: e2e

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node version
        run: node -v

      - name: Zip
        id: pluginmachine
        uses: imaginarymachines/builder-action@main
        with:
          token:  ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          pluginDir: ${{ github.workspace }}

  create-wp-for-testing:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: instawp/wordpress-testing-automation@main
        id: create-wp
        if: github.event.action == 'opened' || github.event.action = 'edited'
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: vendor
          REPO_ID: 4
          INSTAWP_ACTION: create-site-template
          ARTIFACT_URL: ${{steps.pluginmachine.outputs.upload}}
      - run: echo URL ${{ steps.create-wp.outputs.instawp_url }}
        shell: bash

  destroy-wp-after-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        if: github.event.action == 'closed' || github.event.action == 'merged'
        id: detroy-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: vendor
          REPO_ID: 4
          INSTAWP_ACTION: destroy-site
