name: WordPress Tests

# Run on push
on:
  push:
    # any branch
    branches:
      - '*'
      # If files matching these patterns have changed
    paths:
      - 'composer.json'
      - '**.php'
      - readme.txt
      - .github/workflows/wordpress.yml

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ "7.2", "7.4" ]
        wordpress-version: [ latest ]
    steps:

      # Set up plugin
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker Compose Version
        run: docker-compose -v

      ## PHP
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
      - name: PHP Version
        run: php -v

      ## Composer
      - name: Get Composer Cache Directory
        id: get-composer-cache-dir # Instead of composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      # Run integration tests
      - name: PHP Version
        env:
          WORDPRESS_VERSION: "5.8"
          PHP_IMAGE_TAG: "7.2"
        run: docker-compose run phpunit php --version
      - name: Tests
        env:
          WORDPRESS_VERSION: "5.8"
          PHP_IMAGE_TAG: "7.2"
        run: docker-compose run phpunit phpunit --config=./tests/phpunit-integration.xml
